name: Deploy dev

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to rebuild-dev
        run: flyctl deploy -c fly.dev.toml -a rebuild-dev
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
